name: generate pacman game

on:
  schedule: # run automatically every 24 hours
  - cron: "* */12 * * *"
  workflow_dispatch: # allows to manually run the job at any time
  push: # run on every push on the master branch
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 先检出output分支，确保我们不会覆盖现有内容
      - name: Checkout output branch
        uses: actions/checkout@v3
        with:
          ref: output
          path: output

      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          
      - name: Copy generated files to output directory
        run: |
          mkdir -p output
          cp -r dist/* output/
          
      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: output
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}