name: Generate Snake Animation

on:
  schedule:
    # 每天中午12点运行
    - cron: "0 12 * * *"
  
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - uses: actions/checkout@v2
      
      # 生成贪吃蛇动画
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: CrayonCreator
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      # 部署到GitHub Pages
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}